api:
  replicas: 1
  hpa:
    minReplicas: 1
    maxReplicas: 2
    cpuAverageUtilization: 50
    memoryAverageUtilization: 70
  resources:
    requests:
      cpu: "200m"
      memory: "1Gi"
    limits:
      cpu: "500m"
      memory: "2Gi"

web:
  replicas: 1
  hpa:
    minReplicas: 1
    maxReplicas: 2
    cpuAverageUtilization: 50
    memoryAverageUtilization: 70
  resources:
    requests:
      cpu: "200m"
      memory: "1Gi"
    limits:
      cpu: "500m"
      memory: "2Gi"
